"""
Research Reports page.

Displays the full markdown research reports generated by HDRP.
"""

from dash import html, dcc, dash_table
import dash_dangerously_set_inner_html as dhtml

from HDRP.dashboard.data_loader import list_available_reports, load_report_content, load_report_metadata
from HDRP.dashboard.layout import create_info_tooltip


def markdown_to_html(markdown_text: str) -> str:
    """
    Convert markdown to HTML for display.
    Uses a simple approach with common markdown patterns.
    """
    try:
        import markdown
        return markdown.markdown(
            markdown_text,
            extensions=['fenced_code', 'tables', 'nl2br', 'sane_lists']
        )
    except ImportError:
        # Fallback if markdown library not available
        # Just wrap in pre tags for now
        return f"<pre style='white-space: pre-wrap; word-wrap: break-word;'>{markdown_text}</pre>"


def create_reports_page(selected_run_id: str = None):
    """Create the research reports viewing page."""
    reports = list_available_reports()
    
    # If no run selected and reports exist, select the first one
    if not selected_run_id and reports:
        selected_run_id = reports[0]['run_id']
    
    # Load report content if a run is selected
    report_content = None
    report_metadata = None
    if selected_run_id:
        report_content = load_report_content(selected_run_id)
        report_metadata = load_report_metadata(selected_run_id)
    
    # Format reports for dropdown
    report_options = []
    for report in reports:
        label = f"{report['query'][:50]}{'...' if len(report['query']) > 50 else ''} ({report['timestamp'][:10]})"
        if not report['query']:
            label = f"Report {report['run_id'][:8]} ({report['timestamp'][:10]})"
        report_options.append({
            'label': label,
            'value': report['run_id']
        })
    
    if not report_options:
        report_options = [{'label': 'No reports available', 'value': ''}]
    
    # Format reports for table
    table_data = []
    for report in reports:
        short_run_id = report['run_id'][:8] if len(report['run_id']) > 8 else report['run_id']
        query_text = report.get('query', '') or 'Untitled Research'
        if len(query_text) > 50:
            query_display = query_text[:47] + '...'
        else:
            query_display = query_text
        
        table_data.append({
            'query': query_display,
            'run_id': short_run_id,
            'full_run_id': report['run_id'],
            'timestamp': report['timestamp'][:19] if report['timestamp'] else '',
            'claims': f"{report.get('verified_claims', 0)}/{report.get('total_claims', 0)}",
            'size': f"{report['size_bytes'] / 1024:.1f} KB",
        })
    
    # Build the page layout
    children = [
        # Page header
        html.Div(
            className="page-header",
            children=[
                html.Div([
                    html.H1("Research Reports", className="page-title", style={"display": "inline-block", "marginRight": "0"}),
                    create_info_tooltip(
                        "reports-info",
                        "View the full research reports generated by HDRP. These are comprehensive markdown documents with verified claims, citations, and analysis."
                    ),
                ]),
                html.P("View complete research outputs", className="page-subtitle"),
            ]
        ),
    ]
    
    if not reports:
        # Empty state
        children.append(
            html.Div(
                className="card",
                style={"textAlign": "center", "padding": "48px"},
                children=[
                    html.Div("📄", style={"fontSize": "64px", "marginBottom": "16px"}),
                    html.H2("No Research Reports Found", style={"marginBottom": "12px"}),
                    html.P(
                        "Research reports will appear here after running queries.",
                        style={"color": "#8b949e", "marginBottom": "24px"}
                    ),
                    dcc.Link(
                        html.Button("Run a Query", className="btn btn-primary"),
                        href="/query",
                    ),
                ]
            )
        )
    else:
        # Report selector and viewer
        children.extend([
            # Controls
            html.Div(
                className="card",
                style={"marginBottom": "24px"},
                children=[
                    html.Div(
                        style={"display": "flex", "gap": "16px", "alignItems": "center"},
                        children=[
                            html.Div(
                                className="form-group",
                                style={"flex": "1", "marginBottom": "0"},
                                children=[
                                    html.Label("Select Report:", className="form-label"),
                                    dcc.Dropdown(
                                        id="report-selector",
                                        options=report_options,
                                        value=selected_run_id if selected_run_id else (reports[0]['run_id'] if reports else None),
                                        placeholder="Select a report...",
                                        clearable=False,
                                        className="dropdown",
                                    ),
                                ]
                            ),
                            html.Button(
                                "↻ Refresh",
                                id="refresh-reports-btn",
                                className="btn btn-secondary",
                                style={"marginTop": "28px"},
                            ),
                        ]
                    ),
                ]
            ),
            
            # Report metadata (if available)
            html.Div(
                id="report-metadata-section",
                className="card",
                style={"marginBottom": "24px", "display": "block" if report_metadata else "none"},
                children=[
                    html.Div(
                        className="card-header",
                        children=[html.H3("Report Overview", className="card-title")]
                    ),
                    html.Div(
                        id="report-metadata-content",
                        style={"padding": "16px"},
                        children=_create_metadata_display(report_metadata) if report_metadata else []
                    ),
                ] if report_metadata else []
            ),
            
            # Report viewer
            html.Div(
                className="card",
                children=[
                    html.Div(
                        className="card-header",
                        style={"display": "flex", "justifyContent": "space-between", "alignItems": "center"},
                        children=[
                            html.H3("Report Content", className="card-title"),
                            html.Div([
                                html.Button(
                                    "📥 Download Markdown",
                                    id="download-report-btn",
                                    className="btn btn-secondary btn-sm",
                                ),
                                dcc.Download(id="download-report"),
                            ]) if selected_run_id else None,
                        ]
                    ),
                    html.Div(
                        id="report-content-area",
                        className="report-viewer",
                        children=_create_report_display(report_content) if report_content else [
                            html.Div(
                                style={"padding": "48px", "textAlign": "center", "color": "#8b949e"},
                                children="No report content available."
                            )
                        ]
                    ),
                ]
            ),
        ])
    
    return html.Div(children)


def _create_metadata_display(metadata: dict) -> list:
    """Create a display for report metadata."""
    if not metadata:
        return []
    
    stats_grid = []
    
    # Create stat cards
    stats = [
        ("Query", metadata.get('query', 'N/A')[:100], "blue"),
        ("Generated", metadata.get('generated_at', 'N/A')[:19], "green"),
        ("Total Claims", str(metadata.get('total_claims', 0)), "purple"),
        ("Verified Claims", str(metadata.get('verified_claims', 0)), "cyan"),
        ("Unique Sources", str(metadata.get('unique_sources', 0)), "orange"),
    ]
    
    for label, value, color in stats:
        if label == "Query" and len(value) > 60:
            # For long queries, make it a full-width display
            stats_grid.append(
                html.Div(
                    style={
                        "gridColumn": "1 / -1",
                        "padding": "12px",
                        "backgroundColor": "#21262d",
                        "borderRadius": "6px",
                        "marginBottom": "12px"
                    },
                    children=[
                        html.Div(label, style={"fontSize": "0.75rem", "color": "#8b949e", "marginBottom": "4px", "textTransform": "uppercase"}),
                        html.Div(value, style={"fontSize": "0.95rem", "color": "#e6edf3"}),
                    ]
                )
            )
        else:
            stats_grid.append(
                html.Div(
                    style={
                        "padding": "12px",
                        "backgroundColor": "#21262d",
                        "borderRadius": "6px",
                        "border": f"1px solid {_get_color(color)}33",
                    },
                    children=[
                        html.Div(label, style={"fontSize": "0.75rem", "color": "#8b949e", "marginBottom": "4px"}),
                        html.Div(value, style={"fontSize": "1.1rem", "fontWeight": "600", "color": _get_color(color)}),
                    ]
                )
            )
    
    return [
        html.Div(
            style={
                "display": "grid",
                "gridTemplateColumns": "repeat(auto-fit, minmax(200px, 1fr))",
                "gap": "12px",
            },
            children=stats_grid
        )
    ]


def _get_color(name: str) -> str:
    """Get a color hex code by name."""
    colors = {
        'blue': '#58a6ff',
        'green': '#3fb950',
        'purple': '#a371f7',
        'cyan': '#39c5cf',
        'orange': '#d29922',
        'red': '#f85149',
    }
    return colors.get(name, '#8b949e')


def _create_report_display(content: str) -> list:
    """Create the report content display."""
    if not content:
        return [html.Div("No content available.", style={"padding": "24px", "color": "#8b949e"})]
    
    # Use dcc.Markdown for better markdown rendering
    return [
        dcc.Markdown(
            content,
            className="markdown-content",
            dangerously_allow_html=False,
        )
    ]
