#!/usr/bin/env python3
"""
HDRP CLI

Lightweight command-line interface for running the HDRP research pipeline
end-to-end using the Python services and pluggable search providers
(Tavily or simulated).

Usage examples:

    # With Tavily (requires TAVILY_API_KEY)
    export TAVILY_API_KEY="your-key-here"
    python -m HDRP.cli --query "Latest developments in quantum computing"

    # With simulated provider (no external calls)
    python -m HDRP.cli --query "Test query" --provider simulated
"""

import argparse
import os
import sys
from typing import Optional

from HDRP.tools.search.factory import SearchFactory
from HDRP.services.researcher.service import ResearcherService
from HDRP.services.critic.service import CriticService
from HDRP.services.synthesizer.service import SynthesizerService
from HDRP.services.shared.logger import ResearchLogger


def _build_search_provider(
    provider: str,
    api_key: Optional[str],
) -> object:
    """
    Construct a search provider using the existing SearchFactory.

    - When provider == "tavily", prefer explicit api_key if given,
      otherwise fall back to TAVILY_API_KEY env var.
    - When provider == "simulated", ignore api_key.
    - When provider is omitted, delegate to SearchFactory.from_env().
    """
    provider = (provider or "").strip().lower()

    if not provider:
        # Let factory decide based on HDRP_SEARCH_PROVIDER and friends.
        return SearchFactory.from_env()

    if provider == "tavily":
        # Explicit key wins; otherwise rely on environment.
        effective_key = api_key or os.getenv("TAVILY_API_KEY")
        return SearchFactory.get_provider("tavily", api_key=effective_key)

    if provider == "simulated":
        return SearchFactory.get_provider("simulated")

    raise SystemExit(f"Unknown provider '{provider}'. Use 'tavily' or 'simulated'.")


def _run_pipeline(
    query: str,
    provider: str,
    api_key: Optional[str],
    output_path: Optional[str],
    verbose: bool,
) -> int:
    """Execute the core HDRP research → critic → synthesize pipeline."""
    # Single run_id shared across components for joined logging.
    run_logger = ResearchLogger("cli")
    run_id = run_logger.run_id

    if verbose:
        print(f"[hdrp-cli] run_id={run_id}")
        print(f"[hdrp-cli] provider={provider or 'auto'}")

    # 1. Build search provider (Tavily or simulated).
    try:
        search_provider = _build_search_provider(provider, api_key)
    except SystemExit:
        # Re-raise to allow clean exit with message
        raise
    except Exception as exc:
        print(f"[hdrp-cli] Failed to initialize search provider: {exc}", file=sys.stderr)
        return 1

    # 2. Initialize services.
    researcher = ResearcherService(search_provider, run_id=run_id)
    critic = CriticService(run_id=run_id)
    synthesizer = SynthesizerService()

    if verbose:
        print(f"[hdrp-cli] Researching: {query!r}")

    # 3. Research.
    try:
        claims = researcher.research(query, source_node_id="root_research")
    except Exception as exc:
        print(f"[hdrp-cli] Research failed: {exc}", file=sys.stderr)
        return 1

    if verbose:
        print(f"[hdrp-cli] Retrieved {len(claims)} raw claims")

    if not claims:
        print("No information found for this query.")
        return 0

    # 4. Critic: verify claims.
    critique_results = critic.verify(claims, task=query)
    verified_count = sum(1 for r in critique_results if r.is_valid)

    if verbose:
        rejected_count = len(critique_results) - verified_count
        print(f"[hdrp-cli] Verified={verified_count}, Rejected={rejected_count}")

    # 5. Synthesize human-readable report.
    context = {
        "report_title": f"HDRP Research Report: {query}",
        "introduction": (
            "This report was generated by the Hierarchical Deep Research Planner (HDRP) "
            "pipeline using structured claims with explicit source traceability."
        ),
    }
    report = synthesizer.synthesize(critique_results, context=context)

    if output_path:
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(report)
            if verbose:
                print(f"[hdrp-cli] Report written to {output_path}")
        except OSError as exc:
            print(f"[hdrp-cli] Failed to write report to {output_path}: {exc}", file=sys.stderr)
            return 1
    else:
        # Print to stdout.
        print(report)

    return 0


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="hdrp-cli",
        description="Run the HDRP research pipeline on a single query.",
    )
    parser.add_argument(
        "--query",
        "-q",
        required=True,
        help="Research query or objective to investigate.",
    )
    parser.add_argument(
        "--provider",
        "-p",
        choices=["tavily", "simulated"],
        default=None,
        help="Search provider to use. "
        "If omitted, HDRP_SEARCH_PROVIDER/TAVILY_* env vars are used.",
    )
    parser.add_argument(
        "--api-key",
        dest="api_key",
        default=None,
        help="Explicit API key for Tavily; overrides TAVILY_API_KEY env var "
        "when --provider=tavily.",
    )
    parser.add_argument(
        "--output",
        "-o",
        dest="output_path",
        default=None,
        help="If provided, write the final report to this file instead of stdout.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging to stdout.",
    )

    args = parser.parse_args(argv)

    return _run_pipeline(
        query=args.query,
        provider=args.provider,
        api_key=args.api_key,
        output_path=args.output_path,
        verbose=args.verbose,
    )


if __name__ == "__main__":
    raise SystemExit(main())


